### PR TITLE
Fix select branch list scrolling

### LINKED ISSUE #368: correct scrolling on branches list
the branch list uses the *old* scrolling mechanism instead of only scrolling once you go beyond the height of the visible area.

see scrolling in diff/revlog for reference

### PR DESCRIPTION
**Pull request by WizardOhio24**
Closes #368 

The scrolling in branch list is now the same as the commit-list and the file-list, in that it scrolls only at the top or the bottom and can change speed.

### CODE REVIEW

File: src/components/select_branch.rs [hunk 1]
```diff
@@ -31,6 +37,8 @@ pub struct SelectBranchComponent {
     branch_names: Vec<BranchForDisplay>,
     visible: bool,
     selection: u16,
+    scroll_state: (Instant, f32),
```
Comment (extrawurst) [inline src/components/select_branch.rs:40]: we do not need the time based scroll acceleration for this list here. this is a special case for the revlog tab

Comment (WizardOhio24) [reply src/components/select_branch.rs:40]: With this it might be easier/faster to scroll through branches if there are a lot of branches to scroll through; should this be a config option?  So if you're on a massive repo, you can run through the branches quickly, like the commits.

Comment (extrawurst) [reply src/components/select_branch.rs:40]: I did this for repos with >1m commits like the linux repo. I really don't see this necessary for the branch list. if the branches go into the thousands we will have other issues to deal with. let's keep this change to the minimum. otherwise I see no reason why not every single scrollable list should not have the same functionality

Comment (WizardOhio24) [reply src/components/select_branch.rs:40]: Fair enough, it is something to consider, to make every scrollable list have time based scroll acceleration(perhaps as an option, I would use it), but not for this PR.

**Comment by extrawurst** [comment]
this crashes on small terminals:
```rust
panic: PanicInfo { payload: Any, message: Some(attempt to subtract with overflow), location: Location { file: "src/components/select_branch.rs", line: 62, col: 35 } }
trace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.53/src/backtrace/libunwind.rs:100:5
      backtrace::backtrace::trace_unsynchronized
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.53/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.53/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.53/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.53/src/capture.rs:140:22
   4: gitui::set_panic_handlers::{{closure}}
             at src/main.rs:300:25
   5: std::panicking::rust_panic_with_hook
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:573:17
   6: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476:9
   7: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153:18
   8: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475:5
   9: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85:14
  10: core::panicking::panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:50:5
  11: <gitui::components::select_branch::SelectBranchComponent as gitui::components::DrawableComponent>::draw
             at src/components/select_branch.rs:62:35
  12: gitui::app::App::draw_popups
             at src/app.rs:626:9
  13: gitui::app::App::draw
             at src/app.rs:205:9
  14: gitui::draw::{{closure}}
             at src/main.rs:184:25
  15: tui::terminal::Terminal<B>::draw
             at /Users/stephan/.cargo/registry/src/github.com-1ecc6299db9ec823/tui-0.12.0/src/terminal.rs:259:9
  16: gitui::draw
             at src/main.rs:183:5
  17: gitui::main
             at src/main.rs:149:13
  18: core::ops::function::FnOnce::call_once
             at /Users/stephan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
  19: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /Users/stephan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/sys_common/backtrace.rs:137:18
  20: std::rt::lang_start::{{closure}}
             at /Users/stephan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:66:18
  21: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:259:13
      std::panicking::try::do_call
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:373:40
      std::panicking::try
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:337:19
      std::panic::catch_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panic.rs:379:14
      std::rt::lang_start_internal
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/rt.rs:51:25
  22: std::rt::lang_start
             at /Users/stephan/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/library/std/src/rt.rs:65:5
  23: _main
```

**Comment by WizardOhio24** [comment]
Fixed

**Comment by extrawurst** [comment]
@WizardOhio24 thank you so much for for continuing support!❤️
