### PR TITLE
proper pre-push hook implementation

### LINKED ISSUE #2809: Pushing throws pre-push hook error on repository with LFS.
**Describe the bug**
After updating to v0.28.0 I consistently receive the following error when attempting to push a change:

```
pre-push hook failed:
This should be run through Git's pre-push hook.  Run `git lfs update` to install it.
```

**To Reproduce**
1. Press `P`

**Expected behavior**
Changes are pushed without error.

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS Tahoe version 26.1`
 - GitUI Version `0.28.0`
 - Rust version: not sure, installed via brew

**Additional context**

The repository that presents the issue uses LFS as recommended by the [Paparazzi](https://github.com/cashapp/paparazzi?tab=readme-ov-file#git-lfs) library. 

Running `git lfs update` does not solve the issue. Removing `.git/hooks/pre-push` fixes the issue but obviously breaks LFS. Running `git lfs update` brings back the problem. Here are the contents of the generated pre-push hook:

```sh
#!/bin/sh
command -v git-lfs >/dev/null 2>&1 || { printf >&2 "\n%s\n\n" "This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting the 'pre-push' file in the hooks directory (set by 'core.hookspath'; usually '.git/hooks')."; exit 2; }
git lfs pre-push "$@"
```

I also ensured to run `chmod +x .git/hooks/pre-push` but it made no difference.

### PR DESCRIPTION
**Pull request by extrawurst**
closes #2809

### CODE REVIEW

**Comment by argenkiwi** [comment]
I can confirm the issue appears to be gone when building from this branch. 

I am not that familiar with Rust development, so let me share the steps I followed to ensure I am not missing anything:
1. Uninstalled gitui
2. Cloned this repo
3. Checked out the `pre-push-with-lfs` branch
4. Executed `cargo build`
5. Switched to the folder of the repo that presented the original issue
6. Executed `cargo build --manifest-path path/to/gitui/repo/Cargo.toml`
7. Successfully performed a push by pressing P

**Comment by extrawurst** [comment]
> I can confirm the issue appears to be gone when building from this branch.
> 
> I am not that familiar with Rust development, so let me share the steps I followed to ensure I am not missing anything:

The way you did it works, if you wanna use this custom build in a few more places to test, simply run `make install` and it will install a custom build `gitui` in your system that you can invoke just like your prior installed gitui version

**Comment by argenkiwi** [comment]
> > I can confirm the issue appears to be gone when building from this branch.
> > I am not that familiar with Rust development, so let me share the steps I followed to ensure I am not missing anything:
> 
> The way you did it works, if you wanna use this custom build in a few more places to test, simply run `make install` and it will install a custom build `gitui` in your system that you can invoke just like your prior installed gitui version

Excellent, that will get me through the last work day of the year. Thank you for solving the issue so quickly. Have a great end of the year.

**Comment by cruessler** [comment]
@extrawurst I’ll try and have a look later this week! (I want to set up a proper repository with `git lfs` hooks for testing.)

**Comment by cruessler** [comment]
I started reviewing this PR, but since it’s a lot of new code and I’m not deeply familiar with hooks, it might take a while. :-) I can confirm, though, that the error message mentioned in the bug report is gone. Instead, `git lfs pre-push …` is called as far as I can tell.

File: git2-hooks/src/lib.rs [hunk 1]
```diff
@@ -48,37 +48,99 @@ pub const HOOK_PRE_PUSH: &str = "pre-push";
...
+	Run(HookRunResponse),
 }
 
 impl HookResult {
-	/// helper to check if result is ok
+	/// helper to check if result is ok (hook succeeded with exit code 0)
 	pub const fn is_ok(&self) -> bool {
-		matches!(self, Self::Ok { .. })
+		match self {
+			Self::Run(response) => response.code == 0,
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: What about calling `response.is_successful()` and `!response.is_successful()` below? Otherwise, can `HookRunResponse::is_successful` be deleted?

File: git2-hooks/src/lib.rs [hunk 2]
```diff
@@ -48,37 +48,99 @@ pub const HOOK_PRE_PUSH: &str = "pre-push";
...
+#[derive(Clone, Debug, PartialEq, Eq)]
+pub struct PrePushRef {
+	pub local_ref: String,
+	pub local_oid: Option<Oid>,
+	pub remote_ref: String,
+	pub remote_oid: Option<Oid>,
+}
+
+impl PrePushRef {
+	#[must_use]
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Why is this `#[must_use]`?

File: git2-hooks/src/lib.rs [hunk 3]
```diff
@@ -48,37 +48,99 @@ pub const HOOK_PRE_PUSH: &str = "pre-push";
...
+			remote_ref: remote_ref.into(),
+			remote_oid,
+		}
+	}
+
+	fn format_oid(oid: Option<Oid>) -> String {
+		oid.map_or_else(|| "0".repeat(40), |id| id.to_string())
+	}
+
+	#[must_use]
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Why is this `#[must_use]`?

File: git2-hooks/src/lib.rs [hunk 4]
```diff
@@ -48,37 +48,99 @@ pub const HOOK_PRE_PUSH: &str = "pre-push";
...
+		Self {
+			local_ref: local_ref.into(),
+			local_oid,
+			remote_ref: remote_ref.into(),
+			remote_oid,
+		}
+	}
+
+	fn format_oid(oid: Option<Oid>) -> String {
+		oid.map_or_else(|| "0".repeat(40), |id| id.to_string())
```
Comment (cruessler) [inline git2-hooks/src/lib.rs:87]: What about adding a comment explaining the else branch? (I now know why it’s this way, but I only know because I read the docs: https://git-scm.com/docs/githooks#_pre_push.)

File: git2-hooks/src/lib.rs [hunk 5]
```diff
@@ -339,22 +475,16 @@ exit 0
...
 
-		let HookResult::RunNotSuccessful {
-			code,
-			stdout,
-			stderr,
-			hook: h,
-		} = result
-		else {
+		let HookResult::Run(response) = result else {
 			unreachable!("run_hook should've failed");
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: This message is not accurate anymore as the alternative to `HookResult::Run` is `HookResult::NoHookFound`. Other tests don’t have a message, so that’s also an option.

File: git2-hooks/src/lib.rs [hunk 6]
```diff
@@ -633,7 +763,7 @@ exit 0
 		)
 		.unwrap();
 
-		assert!(matches!(res, HookResult::Ok { .. }));
+		assert!(res.is_ok());
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: This will also be `true` when res is `HookResult::NoHookFound`. Is that the desired behaviour? I feel like the code might become easier to reason about if `HookResult::is_ok` were removed or renamed, even if that would make certain call sites more verbose.

File: git2-hooks/src/lib.rs [hunk 7]
```diff
@@ -684,9 +813,25 @@ exit 0
...
+			&repo,
+			None,
+			Some("origin"),
+			"https://example.com/repo.git",
+			&updates,
+		)
+		.unwrap();
 
-		assert!(matches!(res, HookResult::Ok { .. }));
+		assert!(res.is_ok());
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Similar to the above comment on `res.is_ok`.

File: git2-hooks/src/lib.rs [hunk 8]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+		let res = hooks_pre_push(
+			&repo,
+			None,
+			None,
+			"https://example.com/repo.git",
+			&updates,
+		)
+		.unwrap();
+
+		assert!(res.is_ok(), "Expected Ok result, got: {res:?}");
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: I think an assertion on `response.stdout` should be added here. (The subsequent test’s assertions can basically be copied and changed.)

File: git2-hooks/src/lib.rs [hunk 9]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+				.contains("remote_url=https://example.com/repo.git"),
+			"Expected stdout to contain URL, got: {}",
+			response.stdout
+		);
+		assert!(
+			response.stdout.contains("stdin_length=")
+				&& !response.stdout.contains("stdin_length=0"),
+			"Expected stdin to be non-empty, got: {}",
+			response.stdout
+		);
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Would it make sense to turn this into `assert_eq!(response.stdout, "…")`? I feel that would make the intent clearer.

File: git2-hooks/src/lib.rs [hunk 10]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+		let HookResult::Run(response) = res else {
+			unreachable!("Expected Run result, got: {res:?}")
+		};
+
+		assert!(response.is_successful());
+		assert_eq!(response.stdout, expected_stdin);
+		assert!(
+			response
+				.stdout
+				.contains("0000000000000000000000000000000000000000"),
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Would it make sense to run `assert_eq!(response.stdout, "…")`, in order to make the context more clear?

File: git2-hooks/src/lib.rs [hunk 11]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+				// Success - arguments were correct
+			}
+			HookResult::Run(response) => {
+				panic!(
+					"Hook failed validation!\nstdout: {}\nstderr: {}",
+					response.stdout, response.stderr
+				);
+			}
+			_ => unreachable!(),
+		}
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Could this be turned into an `assert!(matches!(…))`?

File: git2-hooks/src/lib.rs [hunk 12]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+    echo \"ERROR: Expected remote name 'origin', got '$1'\" >&2
+    exit 1
+fi
+if [ \"$2\" != \"https://github.com/user/repo.git\" ]; then
+    echo \"ERROR: Expected URL 'https://github.com/user/repo.git', got '$2'\" >&2
+    exit 1
+fi
+echo \"Arguments verified: remote=$1, url=$2\"
+exit 0
+	";
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Did you consider echoing the inputs and running the validation in Rust? Does running the validations in Bash add anything we can’t accomplish in Rust?

File: git2-hooks/src/lib.rs [hunk 13]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+		let hook = b"#!/bin/sh
+	stdin_content=$(cat)
+	if [ -z \"$stdin_content\" ]; then
+	    echo \"stdin was unexpectedly empty\" >&2
+	    exit 1
+	fi
+	echo \"stdin_length=${#stdin_content}\"
+	echo \"stdin_content=$stdin_content\"
+	exit 0
+		";
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Similar to the above test: could/should this logic be moved to Rust?

File: git2-hooks/src/lib.rs [hunk 14]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+# Verify it has 4 space-separated fields
+field_count=$(echo \"$stdin_content\" | awk '{print NF}')
+if [ \"$field_count\" != \"4\" ]; then
+    echo \"ERROR: Expected 4 fields, got $field_count\" >&2
+    exit 1
+fi
+
+echo \"SUCCESS: Received properly formatted stdin\"
+exit 0
+	";
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Similar to the above tests: is this something we can/want to do in Rust? My first thought would be echoing stdin to stdout and then running `assert_eq!(response.stdout, "…")`, but I might be missing something.

File: git2-hooks/src/lib.rs [hunk 15]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+			"https://github.com/user/repo.git",
+			&updates,
+		)
+		.unwrap();
+
+		let HookResult::Run(response) = res else {
+			panic!("Expected Run result, got: {res:?}")
+		};
+
+		// This should now pass with proper stdin implementation
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Can this comment be removed?

File: git2-hooks/src/lib.rs [hunk 16]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+		assert!(
+			response.is_successful(),
+			"Hook should succeed with proper stdin.\nstdout: {}\nstderr: {}",
+			response.stdout,
+			response.stderr
+		);
+
+		// Verify the hook received proper stdin format
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Can this comment be removed?

File: git2-hooks/src/lib.rs [hunk 17]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+				None, // Don't update any refs
+				&sig,
+				&sig,
+				"old backup commit",
+				&tree,
+				&[], // No parents
+			)
+			.unwrap();
+
+		// Now create backup/master pointing to this old commit
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Can this comment be removed?

File: git2-hooks/src/lib.rs [hunk 18]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+		repo.reference(
+			"refs/remotes/backup/master",
+			old_commit,
+			true,
+			"create backup/master at old commit",
+		)
+		.unwrap();
+
+		// Configure branch.master.remote and branch.master.merge to set upstream
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Can this comment be removed?

File: git2-hooks/src/lib.rs [hunk 19]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+    exit 0
+fi
+
+echo "ERROR: Got unexpected SHA: $remote_sha" >&2
+echo "Expected backup/master: {}" >&2
+echo "Or origin/master (bug): {}" >&2
+exit 1
+"#,
+			local_commit, old_commit, old_commit, local_commit
+		);
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Similar to the other tests above.

File: git2-hooks/src/lib.rs [hunk 20]
```diff
@@ -698,12 +843,534 @@ echo 'failed'
...
+			"https://github.com/user/backup-repo.git",
+			&updates,
+		)
+		.unwrap();
+
+		let HookResult::Run(response) = res else {
+			panic!("Expected Run result, got: {res:?}")
+		};
+
+		// This test now passes after fix
```
Comment (cruessler) [inline git2-hooks/src/lib.rs]: Is this an AI artefact? Can it be removed?

File: src/popups/push.rs [hunk 21]
```diff
@@ -144,10 +144,35 @@ impl PushPopup {
 			remote
 		};
 
+		// get remote URL for pre-push hook
```
Comment (cruessler) [inline src/popups/push.rs]: Can this comment be removed?

File: src/popups/push.rs [hunk 22]
```diff
@@ -144,10 +144,35 @@ impl PushPopup {
...
+
 		// run pre push hook - can reject push
-		if let HookResult::NotOk(e) =
-			hooks_pre_push(&self.repo.borrow())?
-		{
+		let repo = self.repo.borrow();
+		if let HookResult::NotOk(e) = hooks_pre_push(
+			&repo,
+			Some(&remote),
+			&remote_url,
```
Comment (cruessler) [inline src/popups/push.rs]: Do we need to pass both `remote` and `remote_url` or could we also get `remote_url` from `remote` in `hooks_pre_push`?

File: src/popups/push_tags.rs [hunk 23]
```diff
@@ -84,10 +84,34 @@ impl PushTagsPopup {
 		&mut self,
 		cred: Option<BasicAuthCredential>,
 	) -> Result<()> {
+		let remote = get_default_remote(&self.repo.borrow())?;
+
+		// get remote URL for pre-push hook
```
Comment (cruessler) [inline src/popups/push_tags.rs]: Can this comment be removed?

File: asyncgit/src/sync/hooks.rs [hunk 24]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+fi
+
+# Validate arguments
+if [ \"$1\" != \"origin\" ]; then
+    echo \"ERROR: Wrong remote: $1\" >&2
+    exit 1
+fi
+
+exit 0
+        ";
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Similar to other tests.

File: asyncgit/src/sync/hooks.rs [hunk 25]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+		let res = git2_hooks::hooks_pre_push(
+			&repo,
+			None,
+			Some("origin"),
+			"https://github.com/test/repo.git",
+			&[update],
+		)
+		.unwrap();
+
+		// Hook should succeed
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Can this comment be removed?

File: asyncgit/src/sync/hooks.rs [hunk 26]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+		assert!(res.is_ok());
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Similar to other tests. I feel like `assert_eq!(response.stdout, "…")` would make this test’s intent more clear.

File: asyncgit/src/sync/hooks.rs [hunk 27]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+exit 0
+        ";
+
+		git2_hooks::create_hook(
+			&repo,
+			git2_hooks::HOOK_PRE_PUSH,
+			hook,
+		);
+
+		// Try to push master branch
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Can this comment be removed?

File: asyncgit/src/sync/hooks.rs [hunk 28]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+		let res = git2_hooks::hooks_pre_push(
+			&repo,
+			None,
+			Some("origin"),
+			"https://github.com/test/repo.git",
+			&[update],
+		)
+		.unwrap();
+
+		// Hook should reject
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Can this comment be removed?

File: asyncgit/src/sync/hooks.rs [hunk 29]
```diff
@@ -248,4 +443,107 @@ mod tests {
...
+
+		// Hook should succeed
+		assert!(res.is_ok());
+	}
+
+	#[test]
+	fn test_pre_push_hook_rejects_based_on_stdin() {
+		let (_td, repo) = repo_init().unwrap();
+
+		// Create a hook that rejects pushes to master branch
```
Comment (cruessler) [inline asyncgit/src/sync/hooks.rs]: Can this comment be removed?

**Review by cruessler — CHANGES_REQUESTED** [review]
As far as I can tell, things are looking good! My understanding is that this PR adds proper passing of arguments and stdin to `pre-push` hook calls, to be more in line with what `git` does.

The changes in `hooks.rs` look good, but I haven’t been able to review them as detailed as the ones in `lib.rs` as this is an area I’m less familiar with.

Some of my comments are repetitive, e. g. ones to the effect of “Can this comment be removed”. I hope that’s more helpful than just a general “Some of the comments could potentially be removed”.

File: asyncgit/src/sync/hooks.rs (hunk 24 above)
Comment (extrawurst) [reply asyncgit/src/sync/hooks.rs]: good catch. will remove

File: asyncgit/src/sync/hooks.rs (hunk 25 above)
Comment (extrawurst) [reply asyncgit/src/sync/hooks.rs]: will remove

File: asyncgit/src/sync/hooks.rs (hunk 26 above)
Comment (extrawurst) [reply asyncgit/src/sync/hooks.rs]: will just remove

File: git2-hooks/src/lib.rs (hunk 1 above)
Comment (extrawurst) [reply git2-hooks/src/lib.rs]: removed that weird api design entirely.

File: git2-hooks/src/lib.rs (hunk 6 above)
Comment (extrawurst) [reply git2-hooks/src/lib.rs]: ok I think its a clearer api design now with a separate call for `did_run_hook` to check in our tests that the hook was actually run

File: src/popups/push.rs (hunk 22 above)
Comment (extrawurst) [reply src/popups/push.rs]: good idea

**Comment by extrawurst** [comment]
@cruessler ok thanks for the intensive review, the result I think is much better, no bash based asserting anymore and a better api on HookResult. Last sanity check please
